SELECT * FROM orders;

CREATE TABLE orders (
id_order NUMBER(38,0) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
purch_amt NUMBER DEFAULT 0,
ord_date DATE DEFAULT SYSDATE,
customer_id NUMBER(38,0) NOT NULL,
salesman_id NUMBER(38,0) NOT NULL,
CONSTRAINT order_pk PRIMARY KEY(id_order),
CONSTRAINT orders_cust_fk FOREIGN KEY(customer_id) REFERENCES customer(customer_id),
CONSTRAINT orders_sales_fk FOREIGN KEY(salesman_id) REFERENCES salesman(salesman_id)
);

DROP TABLE orders;

CREATE SEQUENCE customer_seq START WITH 1;

CREATE TABLE customer (
customer_id NUMBER(38,0) DEFAULT customer_seq.nextval NOT NULL,
cust_name VARCHAR2(100) NOT NULL,
city VARCHAR2(15),
grade NUMBER DEFAULT 0,
salesman_id NUMBER(38,0) NOT NULL,
CONSTRAINT customer_id_pk PRIMARY KEY (customer_id),
CONSTRAINT customer_salesman_fk FOREIGN KEY (salesman_id) REFERENCES salesman (salesman_id)
);

DROP TABLE customer;

CREATE TABLE salesman (
salesman_id NUMBER(38,0) GENERATED by default on null as IDENTITY,
nombre VARCHAR2(100) NOT NULL,
city VARCHAR2(15),
commission NUMBER,
CONSTRAINT salesman_pk PRIMARY KEY(salesman_id)
);
SELECT * FROM salesman;
DROP TABLE salesman;